#include "test_support/native_test_registry.h"

void register_runtime_config_tests(native_test::Registry&);
void register_target_plan_contract_tests(native_test::Registry&);
void register_committed_capture_observation_tests(native_test::Registry&);
void register_input_edge_reducer_tests(native_test::Registry&);
void register_aim_scope_reducer_tests(native_test::Registry&);
void register_intent_filter_tests(native_test::Registry&);
void register_operation_intent_tests(native_test::Registry&);
void register_target_state_reducers_tests(native_test::Registry&);
void register_ads_lifecycle_reducer_tests(native_test::Registry&);
void register_ads_reacquisition_reducer_tests(native_test::Registry&);
void register_control_pipeline_primitives_tests(native_test::Registry&);
void register_target_pipeline_integration_tests(native_test::Registry&);
void register_target_coordinator_tests(native_test::Registry&);
void register_ads_acquisition_controller_tests(native_test::Registry&);
void register_bodylock_follow_controller_tests(native_test::Registry&);
void register_bodylock_target_motion_observer_tests(native_test::Registry&);
void register_aim_dynamics_shaper_tests(native_test::Registry&);
void register_aim_response_estimator_tests(native_test::Registry&);
void register_response_model_aim_solver_tests(native_test::Registry&);
void register_target_geometry_tests(native_test::Registry&);
void register_build_family_tests(native_test::Registry&);
void register_resize_contract_tests(native_test::Registry&);
void register_target_selector_tests(native_test::Registry&);
void register_color_readback_tests(native_test::Registry&);
void register_io_recovery_policy_tests(native_test::Registry&);
void register_controller_protocol_tests(native_test::Registry&);
void register_vision_service_tests(native_test::Registry&);
void register_runtime_timing_tests(native_test::Registry&);
void register_ads_snap_deadline_release_incident(native_test::Registry&);
void register_acquisition_gesture_purpose_incident_regression(native_test::Registry&);
void register_ads_center_cross_late_exit_incident_regression(native_test::Registry&);
void register_ads_close_acquisition_pacing_incident_regression(native_test::Registry&);
void register_ads_initial_scope_existing_target_incident_regression(native_test::Registry&);
void register_ads_scope_ready_authority_incident_regression(native_test::Registry&);
void register_ads_single_press_token_incident_regression(native_test::Registry&);
void register_ads_snap_core_contract_incident_regression(native_test::Registry&);
void register_bodylock_high_frequency_incident_regression(native_test::Registry&);
void register_bodylock_position_motion_conflict_incident_regression(native_test::Registry&);
void register_bodylock_target_direction_latency_incident_regression(native_test::Registry&);
void register_bodylock_target_motion_total_incident_regression(native_test::Registry&);
void register_close_cue_hold_authority_incident_regression(native_test::Registry&);
void register_controller_product_contract_incident_regression(native_test::Registry&);
void register_far_selected_person_ads_admission_incident_regression(native_test::Registry&);
void register_manual_ai_arbitration_continuity_incident_regression(native_test::Registry&);
void register_manual_residual_authority_incident_regression(native_test::Registry&);
void register_neutral_drift_arbitration_incident_regression(native_test::Registry&);
void register_vertical_correction_release_incident_regression(native_test::Registry&);
void register_ads_dynamic_pickup_roi_incident_regression(native_test::Registry&);

int main(int argc, char** argv) {
    native_test::Registry registry;
    register_runtime_config_tests(registry);
    register_target_plan_contract_tests(registry);
    register_committed_capture_observation_tests(registry);
    register_input_edge_reducer_tests(registry);
    register_aim_scope_reducer_tests(registry);
    register_intent_filter_tests(registry);
    register_operation_intent_tests(registry);
    register_target_state_reducers_tests(registry);
    register_ads_lifecycle_reducer_tests(registry);
    register_ads_reacquisition_reducer_tests(registry);
    register_control_pipeline_primitives_tests(registry);
    register_target_pipeline_integration_tests(registry);
    register_target_coordinator_tests(registry);
    register_ads_acquisition_controller_tests(registry);
    register_bodylock_follow_controller_tests(registry);
    register_bodylock_target_motion_observer_tests(registry);
    register_aim_dynamics_shaper_tests(registry);
    register_aim_response_estimator_tests(registry);
    register_response_model_aim_solver_tests(registry);
    register_target_geometry_tests(registry);
    register_build_family_tests(registry);
    register_resize_contract_tests(registry);
    register_target_selector_tests(registry);
    register_color_readback_tests(registry);
    register_io_recovery_policy_tests(registry);
    register_controller_protocol_tests(registry);
    register_vision_service_tests(registry);
    register_runtime_timing_tests(registry);
    register_ads_snap_deadline_release_incident(registry);
    register_acquisition_gesture_purpose_incident_regression(registry);
    register_ads_center_cross_late_exit_incident_regression(registry);
    register_ads_close_acquisition_pacing_incident_regression(registry);
    register_ads_initial_scope_existing_target_incident_regression(registry);
    register_ads_scope_ready_authority_incident_regression(registry);
    register_ads_single_press_token_incident_regression(registry);
    register_ads_snap_core_contract_incident_regression(registry);
    register_bodylock_high_frequency_incident_regression(registry);
    register_bodylock_position_motion_conflict_incident_regression(registry);
    register_bodylock_target_direction_latency_incident_regression(registry);
    register_bodylock_target_motion_total_incident_regression(registry);
    register_close_cue_hold_authority_incident_regression(registry);
    register_controller_product_contract_incident_regression(registry);
    register_far_selected_person_ads_admission_incident_regression(registry);
    register_manual_ai_arbitration_continuity_incident_regression(registry);
    register_manual_residual_authority_incident_regression(registry);
    register_neutral_drift_arbitration_incident_regression(registry);
    register_vertical_correction_release_incident_regression(registry);
    register_ads_dynamic_pickup_roi_incident_regression(registry);
    return native_test::run(registry, argc, argv, "NativeBaseTests");
}
