#include "test_support/native_test_registry.h"
void register_desktop_session_tests(native_test::Registry&);
void register_state_machine_replay_tests(native_test::Registry&);
void register_state_machine_contract_tests(native_test::Registry&);

void register_ads_bodylock_september_incidents(native_test::Registry&);
void register_startup_response_prior_tests(native_test::Registry&);
void register_touchpad_fire_tests(native_test::Registry&);
void register_runtime_config_tests(native_test::Registry&);
void register_runtime_reload_policy_tests(native_test::Registry&);
void register_target_plan_contract_tests(native_test::Registry&);
void register_committed_capture_observation_tests(native_test::Registry&);
void register_input_edge_reducer_tests(native_test::Registry&);
void register_aim_scope_reducer_tests(native_test::Registry&);
void register_intent_filter_tests(native_test::Registry&);
void register_operation_intent_tests(native_test::Registry&);
void register_target_state_reducers_tests(native_test::Registry&);
void register_ads_lifecycle_reducer_tests(native_test::Registry&);
void register_ads_reacquisition_reducer_tests(native_test::Registry&);
void register_control_pipeline_primitives_tests(native_test::Registry&);
void register_target_pipeline_integration_tests(native_test::Registry&);
void register_target_coordinator_tests(native_test::Registry&);
void register_ads_acquisition_controller_tests(native_test::Registry&);
void register_bodylock_follow_controller_tests(native_test::Registry&);
void register_bodylock_target_motion_observer_tests(native_test::Registry&);
void register_bodylock_recoil_feedback_incident_tests(native_test::Registry&);
void register_bodylock_motion_anchor_incident_tests(native_test::Registry&);
void register_zero_target_hold_incident(native_test::Registry&);
void register_aim_dynamics_shaper_tests(native_test::Registry&);
void register_aim_response_estimator_tests(native_test::Registry&);
void register_response_model_aim_solver_tests(native_test::Registry&);
void register_target_geometry_tests(native_test::Registry&);
void register_build_family_tests(native_test::Registry&);
void register_resize_contract_tests(native_test::Registry&);
void register_target_selector_tests(native_test::Registry&);
void register_marker_loss_acquisition_incident_tests(native_test::Registry&);
void register_visible_selection_contract_tests(native_test::Registry&);
void register_visible_selection_pipeline_tests(native_test::Registry&);
void register_color_readback_tests(native_test::Registry&);
void register_io_recovery_policy_tests(native_test::Registry&);
void register_controller_protocol_tests(native_test::Registry&);
void register_ds4_output_report_tests(native_test::Registry&);
void register_sdl_gamepad_reader_tests(native_test::Registry&);
void register_vision_service_tests(native_test::Registry&);
void register_runtime_timing_tests(native_test::Registry&);
void register_bodylock_high_frequency_incident_regression(native_test::Registry&);

int main(int argc, char** argv) {
    native_test::Registry registry;
    register_desktop_session_tests(registry);
    register_ads_bodylock_september_incidents(registry);
    register_state_machine_replay_tests(registry);
    register_state_machine_contract_tests(registry);
    register_startup_response_prior_tests(registry);
    register_touchpad_fire_tests(registry);
    register_runtime_config_tests(registry);
    register_runtime_reload_policy_tests(registry);
    register_target_plan_contract_tests(registry);
    register_committed_capture_observation_tests(registry);
    register_input_edge_reducer_tests(registry);
    register_aim_scope_reducer_tests(registry);
    register_intent_filter_tests(registry);
    register_operation_intent_tests(registry);
    register_target_state_reducers_tests(registry);
    register_ads_lifecycle_reducer_tests(registry);
    register_ads_reacquisition_reducer_tests(registry);
    register_control_pipeline_primitives_tests(registry);
    register_target_pipeline_integration_tests(registry);
    register_target_coordinator_tests(registry);
    register_ads_acquisition_controller_tests(registry);
    register_bodylock_follow_controller_tests(registry);
    register_bodylock_target_motion_observer_tests(registry);
    register_bodylock_recoil_feedback_incident_tests(registry);
    register_bodylock_motion_anchor_incident_tests(registry);
    register_zero_target_hold_incident(registry);
    register_aim_dynamics_shaper_tests(registry);
    register_aim_response_estimator_tests(registry);
    register_response_model_aim_solver_tests(registry);
    register_target_geometry_tests(registry);
    register_build_family_tests(registry);
    register_resize_contract_tests(registry);
    register_target_selector_tests(registry);
    register_marker_loss_acquisition_incident_tests(registry);
    register_visible_selection_contract_tests(registry);
    register_visible_selection_pipeline_tests(registry);
    register_color_readback_tests(registry);
    register_io_recovery_policy_tests(registry);
    register_controller_protocol_tests(registry);
    register_ds4_output_report_tests(registry);
    register_sdl_gamepad_reader_tests(registry);
    register_vision_service_tests(registry);
    register_runtime_timing_tests(registry);
    register_bodylock_high_frequency_incident_regression(registry);
    return native_test::run(registry, argc, argv, "NativeBaseTests");
}
