# GUI and C++ consume the same metadata. Generation needs only CMake, not Python.
set(_catalog "${PROJECT_SOURCE_DIR}/controller_native/editable_parameters.json")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_catalog}")
file(READ "${_catalog}" _json)
string(JSON _version GET "${_json}" schema_version)
if(NOT _version EQUAL 1)
    message(FATAL_ERROR "Unsupported editable parameter catalog version: ${_version}")
endif()
string(JSON _count LENGTH "${_json}" parameters)
math(EXPR _last "${_count}-1")
set(_generated "// Generated from editable_parameters.json; do not edit.\n")
foreach(_i RANGE ${_last})
    foreach(_key path member constant default min max hot_reload preserve_learning)
        string(JSON _${_key} GET "${_json}" parameters ${_i} ${_key})
    endforeach()
    string(REGEX REPLACE "\\.[^.]+$" "" _section "${_path}")
    string(REGEX REPLACE "^.*\\." "" _key "${_path}")
    foreach(_bool hot_reload preserve_learning)
        if(_${_bool})
            set(_${_bool} true)
        else()
            set(_${_bool} false)
        endif()
    endforeach()
    string(MAKE_C_IDENTIFIER "${_path}" _id)
    set(_member_${_id} "${_member}")
    string(APPEND _generated "NATIVE_EDITABLE_FLOAT(\"${_section}\", \"${_key}\", ${_member}, ${_constant}, static_cast<float>(${_default}), static_cast<float>(${_min}), static_cast<float>(${_max}), ${_hot_reload}, ${_preserve_learning})\n")
endforeach()
set(_relations "// Generated relationships.\n")
string(JSON _count LENGTH "${_json}" relations)
math(EXPR _last "${_count}-1")
foreach(_i RANGE ${_last})
    string(JSON _left GET "${_json}" relations ${_i} left)
    string(JSON _right GET "${_json}" relations ${_i} right)
    string(JSON _operator GET "${_json}" relations ${_i} operator)
    if(_operator STREQUAL "lt")
        set(_op "<")
    elseif(_operator STREQUAL "le")
        set(_op "<=")
    else()
        message(FATAL_ERROR "Unsupported editable parameter relationship: ${_operator}")
    endif()
    string(MAKE_C_IDENTIFIER "${_left}" _left_id)
    string(MAKE_C_IDENTIFIER "${_right}" _right_id)
    string(APPEND _relations "NATIVE_PARAMETER_RELATION(\"${_left}\", ${_member_${_left_id}}, ${_op}, ${_member_${_right_id}})\n")
endforeach()
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/generated")
file(CONFIGURE OUTPUT "${PROJECT_BINARY_DIR}/generated/editable_float_parameters.inc" CONTENT "${_generated}" @ONLY)
file(CONFIGURE OUTPUT "${PROJECT_BINARY_DIR}/generated/editable_parameter_relations.inc" CONTENT "${_relations}" @ONLY)
