import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DEFAULT_MODEL_PATH = PROJECT_ROOT / "models" / "yolo26n.pt"
DEFAULT_DATASET_YAML = PROJECT_ROOT / "training_data" / "assembled" / "person_detect_visible" / "dataset.yaml"
DEFAULT_PROJECT_DIR = PROJECT_ROOT / "runs" / "person_train"


def _normalize_cache(value):
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {"false", "none", "no", "off", "0"}:
        return False
    if normalized in {"true", "yes", "on", "1"}:
        return True
    if normalized in {"ram", "disk"}:
        return normalized
    raise argparse.ArgumentTypeError("cache must be one of false, true, ram, or disk")


def _normalize_optional_auto_augment(value):
    normalized = str(value).strip().lower()
    if normalized in {"none", "false", "off", "no", "0", ""}:
        return None
    if normalized in {"randaugment", "augmix", "autoaugment"}:
        return normalized
    raise argparse.ArgumentTypeError("auto augment must be one of none, randaugment, augmix, or autoaugment")


def _parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Train a one-class person detector on the current YOLO26 detect stack.")
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL_PATH, help="Base YOLO model checkpoint.")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATASET_YAML, help="Dataset YAML generated by prepare_person_dataset.py.")
    parser.add_argument("--epochs", type=int, default=80, help="Training epochs.")
    parser.add_argument("--imgsz", type=int, default=896, help="Training image size.")
    parser.add_argument("--batch", type=int, default=16, help="Training batch size.")
    parser.add_argument("--device", default="0", help="CUDA device id, e.g. 0.")
    parser.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Data loader workers. Keep 0 on Windows for stable non-stdin multiprocessing behavior.",
    )
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT_DIR, help="Ultralytics project output directory.")
    parser.add_argument("--name", default="crowdhuman_visible_v1", help="Run name.")
    parser.add_argument(
        "--cache",
        type=_normalize_cache,
        default=False,
        help="Ultralytics cache mode: false, true, ram, or disk. Default is false to avoid pagefile pressure.",
    )
    parser.add_argument("--exist-ok", action="store_true", help="Allow reusing an existing Ultralytics run directory.")
    parser.add_argument("--warmup-epochs", type=float, default=1.0, help="Warmup epochs. Lower values fit short fine-tunes.")
    parser.add_argument("--close-mosaic", type=int, default=0, help="Epochs before the end to disable mosaic.")
    parser.add_argument("--mosaic", type=float, default=0.0, help="Mosaic augmentation probability.")
    parser.add_argument("--erasing", type=float, default=0.0, help="Random erasing probability.")
    parser.add_argument(
        "--auto-augment",
        type=_normalize_optional_auto_augment,
        default=None,
        help="Classification-style auto augmentation policy: none, randaugment, augmix, or autoaugment.",
    )
    parser.add_argument("--scale", type=float, default=0.25, help="Scale augmentation gain.")
    parser.add_argument("--translate", type=float, default=0.05, help="Translate augmentation gain.")
    parser.add_argument("--fliplr", type=float, default=0.5, help="Horizontal flip probability.")
    parser.add_argument("--hsv-h", type=float, default=0.01, help="HSV hue augmentation gain.")
    parser.add_argument("--hsv-s", type=float, default=0.45, help="HSV saturation augmentation gain.")
    parser.add_argument("--hsv-v", type=float, default=0.25, help="HSV value augmentation gain.")
    parser.add_argument("--optimizer", default="auto", help="Ultralytics optimizer, e.g. auto, SGD, Adam, AdamW.")
    parser.add_argument("--lr0", type=float, default=None, help="Initial learning rate. Omit to use Ultralytics default.")
    parser.add_argument("--lrf", type=float, default=None, help="Final learning-rate fraction. Omit to use default.")
    parser.add_argument("--cos-lr", action="store_true", help="Use cosine learning-rate schedule.")
    parser.add_argument("--patience", type=int, default=100, help="Early-stopping patience.")
    return parser.parse_args(argv)


def main(argv=None):
    args = _parse_args(argv)
    from ultralytics import YOLO

    model = YOLO(str(args.model))
    train_kwargs = {
        "data": str(args.data),
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "device": args.device,
        "workers": args.workers,
        "project": str(args.project),
        "name": args.name,
        "exist_ok": args.exist_ok,
        "rect": True,
        "cache": args.cache,
        "single_cls": True,
        "close_mosaic": args.close_mosaic,
        "warmup_epochs": args.warmup_epochs,
        "mosaic": args.mosaic,
        "erasing": args.erasing,
        "auto_augment": args.auto_augment,
        "scale": args.scale,
        "translate": args.translate,
        "fliplr": args.fliplr,
        "hsv_h": args.hsv_h,
        "hsv_s": args.hsv_s,
        "hsv_v": args.hsv_v,
        "optimizer": args.optimizer,
        "cos_lr": args.cos_lr,
        "patience": args.patience,
        "degrees": 0.0,
        "shear": 0.0,
        "perspective": 0.0,
        "copy_paste": 0.0,
        "mixup": 0.0,
    }
    if args.lr0 is not None:
        train_kwargs["lr0"] = args.lr0
    if args.lrf is not None:
        train_kwargs["lrf"] = args.lrf

    results = model.train(**train_kwargs)
    print(f"[Train] complete | save_dir={results.save_dir}")


if __name__ == "__main__":
    main()
