import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ultralytics import YOLO

DEFAULT_MODEL_PATH = PROJECT_ROOT / "models" / "yolo26n.pt"
DEFAULT_DATASET_YAML = PROJECT_ROOT / "training_data" / "assembled" / "person_detect_visible" / "dataset.yaml"
DEFAULT_PROJECT_DIR = PROJECT_ROOT / "runs" / "person_train"


def _parse_args():
    parser = argparse.ArgumentParser(description="Train a one-class person detector on the current YOLO26 detect stack.")
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL_PATH, help="Base YOLO model checkpoint.")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATASET_YAML, help="Dataset YAML generated by prepare_person_dataset.py.")
    parser.add_argument("--epochs", type=int, default=80, help="Training epochs.")
    parser.add_argument("--imgsz", type=int, default=896, help="Training image size.")
    parser.add_argument("--batch", type=int, default=24, help="Training batch size.")
    parser.add_argument("--device", default="0", help="CUDA device id, e.g. 0.")
    parser.add_argument("--workers", type=int, default=8, help="Data loader workers.")
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT_DIR, help="Ultralytics project output directory.")
    parser.add_argument("--name", default="crowdhuman_visible_v1", help="Run name.")
    parser.add_argument("--cache", default="ram", help="Ultralytics cache mode.")
    return parser.parse_args()


def main():
    args = _parse_args()
    model = YOLO(str(args.model))
    results = model.train(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(args.project),
        name=args.name,
        rect=True,
        cache=args.cache,
        single_cls=True,
        close_mosaic=10,
        degrees=0.0,
        shear=0.0,
        perspective=0.0,
        copy_paste=0.0,
        mixup=0.0,
    )
    print(f"[Train] complete | save_dir={results.save_dir}")


if __name__ == "__main__":
    main()
